<a href="https://colab.research.google.com/github/miso-20/statistic_programing_2/blob/main/6_2)_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 프레임 결합
- 데이터 분석에서는 여러 개의 `DataFrame`을 하나로 결합해야 하는 경우가 많다.
- 데이터를 결합하기 위해, 결합의 종류, 필요한 것은 무엇이며, 결합의 결과에 대해 다룬다.

## 1. bind 결합
- Bind 결합은 여러 `DataFrame`을 위아래 또는 좌우로 이어 붙이는 방법이다.
- 위아래 결합은 `row`에 대해 나열, 좌우 결합은 `column`에 대해 나열한다는 개념이다.
- bind 결합에는 `pandas` 모듈에 `concat`함수를 이용한다.
- 함수 적용은 다음과 같다.
```
pd.concat([dataframe_1, dataframe_2, ...], axis, ignore_index)
```
    - axis=0: 행 방향, axis=1: 열 방향 결합을 진행한다. default는 0이다.
    - ignore_index : row와 column들을 reset하기 위해 사용하는 옵션이다. axis = 0 일 경우, 두개의 데이터 셋에서 기존 인덱스들이 그대로 사용된다. default는 False이고, True를 할당하면, 결합하는 방향의 기존 인덱스 대신 새로운 번호를 부여한다.

In [ ]:
import pandas as pd

df_1 = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

df_2 = pd.DataFrame({
    'A': [10, 11, 12],
    'B': [13, 14, 15],
    'C': [16, 17, 18]
})

print(df_1)
print(df_2)

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
    A   B   C
0  10  13  16
1  11  14  17
2  12  15  18

### 1-1) row bind
- `row`에 대한 bind는 다음과 같다.

In [ ]:
pd.concat([df_1, df_2], axis = 0)

    A   B   C
0   1   4   7
1   2   5   8
2   3   6   9
0  10  13  16
1  11  14  17
2  12  15  18

In [ ]:
pd.concat([df_1, df_2])

    A   B   C
0   1   4   7
1   2   5   8
2   3   6   9
0  10  13  16
1  11  14  17
2  12  15  18

In [ ]:
tmp_dat = pd.concat([df_1, df_2])
tmp_dat.loc[1, :]

    A   B   C
1   2   5   8
1  11  14  17

- `df_1`, `df_2`의 기존 행 인덱스가 결합 후에도 유지된다. `ignore_index = True`를 지정하면 다음과 같다.

In [ ]:
pd.concat([df_1, df_2], axis = 0, ignore_index = True)  # 새로운 인덱스 번호 부여! # 밑의 012가 345로 바꼈음

    A   B   C
0   1   4   7
1   2   5   8
2   3   6   9
3  10  13  16
4  11  14  17
5  12  15  18

### 1-2) column bind
- `column`에 대한 bind는 다음과 같다.

In [ ]:
pd.concat([df_1, df_2], axis = 1)

   A  B  C   A   B   C
0  1  4  7  10  13  16
1  2  5  8  11  14  17
2  3  6  9  12  15  18

- row bind와 마찬가지로, 두 DataFrame의 column들이 그대로 결합됨을 알 수 있다. `ignore_index`옵션을 사용하면 다음과 같다.

In [ ]:
pd.concat([df_1, df_2], axis = 1, ignore_index = True)  # 변수 리셋되는 거 알 수 있음

   0  1  2   3   4   5
0  1  4  7  10  13  16
1  2  5  8  11  14  17
2  3  6  9  12  15  18

- `ignore_index = True`를 지정하면 결합 방향의 기존 열 이름 대신 0부터 시작하는 번호가 부여된다.
- 필요한 경우 columns를 이용하여 열 이름을 다시 지정해야 한다.

### 1-3) row, column 갯수가 다른 bind
- column의 갯수 혹은 column의 명이 다르거나, row의 갯수가 다를 경우, 어떻게 결합이 이뤄지나 확인해 보자.

In [ ]:
df_1 = pd.DataFrame({
    'D': [1, 2, 3, 4],
    'B': [4, 5, 6, 7],
    'C': [7, 8, 9, 10]
})

df_2 = pd.DataFrame({
    'A': [10, 11, 12],
    'E': [13, 14, 15],
    'C': [16, 17, 18],
    'B': [19, 20, 21]
})

print(df_1)
print(df_2)

   D  B   C
0  1  4   7
1  2  5   8
2  3  6   9
3  4  7  10
    A   E   C   B
0  10  13  16  19
1  11  14  17  20
2  12  15  18  21

In [ ]:
tmp_dat = pd.concat([df_1, df_2], axis = 0, ignore_index = True)   # 없는 데이터들은 NaN으로 나열됨

In [ ]:
df_1.info()
tmp_dat.info()  # Dtype이 int -> float로 바꼈음  # 데이터 값에 이상이 있다는 걸 바로 알 수 있음 # NaN 결측값이 있다는 거니까

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   D       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 228.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   D       4 non-null      float64
 1   B       7 non-null      int64
 2   C       7 non-null      int64
 3   A       3 non-null      float64
 4   E       3 non-null      float64
dtypes: float64(3), int64(2)
memory usage: 412.0 bytes

- row bind의 경우, 동시에 존재하는 column(같은 이름을 가지는 변수)은 모든 row에 대해 값이 존재하지만, 서로 다르게 존재하는 변수에서는 `NaN(결측값)`이 할당되어 있다.

In [ ]:
pd.concat([df_2, df_1], axis = 1)

      A     E     C     B  D  B   C
0  10.0  13.0  16.0  19.0  1  4   7
1  11.0  14.0  17.0  20.0  2  5   8
2  12.0  15.0  18.0  21.0  3  6   9
3   NaN   NaN   NaN   NaN  4  7  10

- 열 방향으로 결합할 때도 행 인덱스를 기준으로 값이 정렬된다.
- 대응되는 값이 없는 위치에는 `NaN`이 저장된다.

### 1-4) type이 다른 경우
- 변수 명은 같지만 저장된 타입이 다른 경우를 확인해 보자.

In [ ]:
df_1 = pd.DataFrame({
    'D': [1, 2, 3, 4],
    'B': [4, 5, 6, 7],
    'C': [7, 8, 9, 10]
})

df_2 = pd.DataFrame({
    'A': [10, 11, 12],
    'E': [13, 14, 15],
    'C': ["a", "b", "c"],
    'B': [19, 20, 21]
})

print(df_1)
print(df_2)

   D  B   C
0  1  4   7
1  2  5   8
2  3  6   9
3  4  7  10
    A   E  C   B
0  10  13  a  19
1  11  14  b  20
2  12  15  c  21

In [ ]:
pd.concat([df_1, df_2], axis = 0, ignore_index = True)

     D   B   C     A     E
0  1.0   4   7   NaN   NaN
1  2.0   5   8   NaN   NaN
2  3.0   6   9   NaN   NaN
3  4.0   7  10   NaN   NaN
4  NaN  19   a  10.0  13.0
5  NaN  20   b  11.0  14.0
6  NaN  21   c  12.0  15.0

In [ ]:
tmp_dat = pd.concat([df_1, df_2], axis = 0, ignore_index = True)
tmp_dat.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   D       4 non-null      float64
 1   B       7 non-null      int64
 2   C       7 non-null      object
 3   A       3 non-null      float64
 4   E       3 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 412.0+ bytes

In [ ]:
pd.concat([df_1, df_2], axis = 0, ignore_index = True).info() # 바로 위랑 같은 뜻

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   D       4 non-null      float64
 1   B       7 non-null      int64
 2   C       7 non-null      object
 3   A       3 non-null      float64
 4   E       3 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 412.0+ bytes

- 같은 변수에 저장된 **** 데이터의 자료형이 다르더라도 `concat`으로 결합할 수 있다. **** 다만 결합 후 자료형은 달라질 수 있다.

# 2. merge 결합

- `merge`는 두 `DataFrame`에서 **기준 변수의 값이 일치하는 행**을 결합하는 방법이다.
- 먼저 결합에 사용할 기준 변수를 지정하는 방법을 살펴본다.

In [ ]:
import pandas as pd

df_1 = pd.DataFrame({
    "name" : ["철수", "영이", "John"],
    "age"  : [23, 34, 19]
})

df_2 = pd.DataFrame({
    "name" : ["철수", "영이", "John"],
    "sex"  : ["M", "F", "M"]
})

print(df_1)
print(df_2)

   name  age
0    철수   23
1    영이   34
2  John   19
   name sex
0    철수   M
1    영이   F
2  John   M

### 2-1) 기준 변수를 이용한 결합

**① 하나의 변수를 기준으로 결합**

- 두 `DataFrame`에 같은 이름의 기준 변수가 있다면 `on`에 해당 열 이름을 지정한다.
- 아래에서는 `name`이 일치하는 행을 결합한다.

In [ ]:
pd.merge(df_1, df_2, on = "name")

   name  age sex
0    철수   23   M
1    영이   34   F
2  John   19   M

In [ ]:
pd.merge(df_2, df_1, on = "name")  # 열 순서 df_2 먼저 그 다음 df_1

   name sex  age
0    철수   M   23
1    영이   F   34
2  John   M   19

**② 여러 변수를 기준으로 결합**

- 하나의 변수만으로 관측 대상을 구분하기 어려운 경우 여러 변수를 함께 기준으로 사용한다.
- `on=['name', 'year']`와 같이 열 이름을 리스트로 지정하면 이름과 연도가 모두 일치하는 행을 결합한다.
- 아래에서는 이름과 연도가 **모두 일치하는 행**을 결합한다.

In [ ]:
df_score = pd.DataFrame({
    'name': ['철수', '철수', '영희'],
    'year': [2024, 2025, 2024],
    'score': [80, 90, 85]
})

df_class = pd.DataFrame({
    'name': ['철수', '철수', '영희'],
    'year': [2024, 2025, 2024],
    'class': ['A', 'B', 'A']
})

pd.merge(df_score, df_class, on=['name', 'year'])

  name  year  score class
0   철수  2024     80     A
1   철수  2025     90     B
2   영희  2024     85     A

In [ ]:
df_score = pd.DataFrame({   # merge 하기 전 데이터타입 봐야됨
    'name': ['철수', '철수', '영희'],
    'year': [2024, 2025, 2024],
    'score': [80, 90, 85]
})

df_class = pd.DataFrame({
    'name': ['철수', '철수', '영희'],
    'year': ["2024", "2025", "2024"],  # 문자, 숫자 merge 안됨 # 에러남
    'class': ['A', 'B', 'A']
})

pd.merge(df_score, df_class, on=['name', 'year'])

ValueError: You are trying to merge on int64 and str columns for key 'year'. If you wish to proceed you should use pd.concat

In [ ]:
df_score = pd.DataFrame({
    'name': ['철수', '철수', '영희'],
    'year': [2024, 2025, 2024],
    'score': [80, 90, 85]
})

df_class = pd.DataFrame({
    'name': ['철수', '철수', '영희'],
    'year': [2024, 2025, 2024],
    'class': ['A', 'B', 'A']
})

pd.merge(df_score, df_class, on=['name'])  # 이름(name)으로 기준 # 행이 늘어날 수 도 있음!! 중요****

  name  year_x  score  year_y class
0   철수    2024     80    2024     A
1   철수    2024     80    2025     B
2   철수    2025     90    2024     A
3   철수    2025     90    2025     B
4   영희    2024     85    2024     A

- 같은 column이 존재할 경우, x,y로 구분해서 저장해준다.
- observation이 같은 값이 여러 개 존재할 경우, 최종 output이 늘어날 수 있다. ***** **중요*******

- `name`만 기준으로 결합하면 같은 사람의 서로 다른 연도 자료까지 결합될 수 있다.

**③ 두 DataFrame의 기준 변수 이름이 다른 경우**

- 기준 변수의 이름이 다르면 `left_on`과 `right_on`을 각각 지정한다.
- 여러 변수를 기준으로 결합할 때도 리스트를 사용할 수 있다.

In [ ]:
df_class_2 = df_class.rename(columns={'year': '연도'}) # 외우지 마
pd.merge(df_score, df_class_2, left_on=['name', 'year'], right_on=['name', '연도'])

  name  year  score    연도 class
0   철수  2024     80  2024     A
1   철수  2025     90  2025     B
2   영희  2024     85  2024     A

### 2-2) merge의 종류
- `merge`결합에는 총 4가지 결합`(left, right, inner, outer)`네 가지이다. 다음 그림에서 각 방식의 차이를 확인해 보자.
![pic_4](./merge.png)
- 결합에 대한 옵션은 다음과 같다.
```
pd.merge(dataframe_1, dataframe_2, on = "", how = "")
```
    - how option : 두 데이터 셋에 대해 merge의 종류를 input으로 받는다. default는 `inner`이다.

In [ ]:
df_3 = pd.DataFrame({
    "name" : ["철수", "영이"],
    "weight"  : [55, 44]
})

print(df_3)
print(df_1)

  name  weight
0   철수      55
1   영이      44
   name  age
0    철수   23
1    영이   34
2  John   19

In [ ]:
pd.merge(df_1, df_3, on="name")  # 기본 inner join

  name  age  weight
0   철수   23      55
1   영이   34      44

- 기본이 inner이기 때문에 name 기준으로 철수, 영이만 남는다.

In [ ]:
pd.merge(df_1, df_3, on="name", how='left')  # left -> df_1 name 기준으로

   name  age  weight
0    철수   23    55.0
1    영이   34    44.0
2  John   19     NaN

In [ ]:
df_4 = pd.DataFrame({
    "name" : ["철수", "영이", "흥민"],
    "height"  : [167, 175, 183]
})

print(df_4)
print(df_1)

  name  height
0   철수     167
1   영이     175
2   흥민     183
   name  age
0    철수   23
1    영이   34
2  John   19

In [ ]:
pd.merge(df_1, df_4, on="name", how='left')

   name  age  height
0    철수   23   167.0
1    영이   34   175.0
2  John   19     NaN

- df_1에는 흥민이 없고, df_4에는 John이 없음. 따라서 df_1기준(left)으로 John은 최종 데이터에 존재하지만, 흥민은 없고, df_4에 John이 없기 때문에 height에는 NAN이 할당된다.

In [ ]:
pd.merge(df_1, df_4, on="name", how='right') # df_1이 먼저 왔기 때문에 열 순서는 name, age, height임 # 잘 쓰진 않음

  name   age  height
0   철수  23.0     167
1   영이  34.0     175
2   흥민   NaN     183

In [ ]:
pd.merge(df_4, df_1, on="name", how='left') # **left만 나옴 (right는 안 나옴) # 바로 위의 결과와 같음(열 순서만 다르고)

  name  height   age
0   철수     167  23.0
1   영이     175  34.0
2   흥민     183   NaN

- left나 right나 결과에서 나타나는 정보량은 같다. 다만, 기준이 되는 방향이 다를 뿐
- left나 right의 결과를 보면, 흥민이나, John의 정보는 버려진다. 즉, 양쪽에 있는 모든 데이터가 남지 않을 수 있다.

In [ ]:
pd.merge(df_1, df_4, on="name", how='inner')

  name  age  height
0   철수   23     167
1   영이   34     175

In [ ]:
pd.merge(df_1, df_4, on="name", how='outer') # name기준으로 정렬되니까 # 영어 먼저, 한글은 가나다 순

   name   age  height
0  John  19.0     NaN
1    영이  34.0   175.0
2    철수  23.0   167.0
3    흥민   NaN   183.0

- outer는 모든 정보를 항상 살린다.

### 2-3) merge 결합시, 주의사항
- merge 결합할때, 가장 유의해야할 사항들은 많지만, 대표적으로 다음의 몇가지를 꼽을수 있다.
    1. 기준 열의 자료형: 서로 다른 자료형 때문에 결합이 실패하거나 의도한 결과를 얻지 못할 수 있다.
    2. 기준값의 중복: 같은 값이 여러 행에 존재하면 결과 행 수가 증가할 수 있다.
    3. 기준값의 일치 여부: 공백이나 특수문자로 인해 문자열이 다르면 결합되지 않을 수 있다. **** 항상 체크하기!!!!  ** **시험** **
- (1.)에 대한 예시는 다음과 같다.

In [ ]:
df_5 = pd.DataFrame({ # 시험 XXXXXXX
    "name" : ["철수", "영이", "흥민"],
    "height"  : ["167", "175", 183]
})

print(df_5)
print(df_5.info())
print(df_4)
print(df_4.info())

  name height
0   철수    167
1   영이    175
2   흥민    183
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   height  3 non-null      object
dtypes: object(1), str(1)
memory usage: 198.0+ bytes
None
  name  height
0   철수     167
1   영이     175
2   흥민     183
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   height  3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 198.0 bytes
None

In [ ]:
pd.merge(df_4, df_5, on = "height")

  name_x height name_y
0     흥민    183     흥민

- (2.) 에 대한 예시는 다음과 같다.

In [ ]:
df_6 = pd.DataFrame({
    "name" : ["철수", "영이", "John", "철수", "John"],
    "age"  : [23, 34, 19, 20, 25]
})

df_6

   name  age
0    철수   23
1    영이   34
2  John   19
3    철수   20
4  John   25

In [ ]:
df_1

   name  age
0    철수   23
1    영이   34
2  John   19

In [ ]:
pd.merge(df_1, df_6, on="name", how='left')

   name  age_x  age_y
0    철수     23     23
1    철수     23     20
2    영이     34     34
3  John     19     19
4  John     19     25

- `left` 결합에서는 왼쪽 `DataFrame`의 기준값을 유지하지만, 오른쪽에서 같은 값이 여러 번 나타나면 결과 행이 늘어날 수 있다.
- 이는 `df_1` DataFrame에는 철수, John은 1번씩 관측되었지만, `df_5` DataFrame에 2번씩 관측되었기에, 기준이 되는 `df_1`에 두번씩 붙었기 때문에, 발생한다.